# Generated by Django 2.0 on 2020-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=models.CharField(max_length=500),
        ),
    ]
