# Generated by Django 2.0 on 2020-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_auto_20200429_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterModelTable(
            name='upload',
            table='cart',
        ),
    ]
